apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: scraper-scraper-set
  labels:
    type: scraper-scraper-set
spec:
  replicas: 3
  selector:
    matchLabels:
      type: scraper-scraper-pod
  template:
    metadata:
      labels:
        type: scraper-scraper-pod
    spec:
      containers:
        - name: scraper-pod
          imagePullPolicy: Never
          image: scraper:latest
          ports:
            - containerPort: 7021
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: scraper-aws-set
  labels:
    type: scraper-aws-set
spec:
  replicas: 3
  selector:
    matchLabels:
      type: scraper-aws-pod
  template:
    metadata:
      labels:
        type: scraper-aws-pod
    spec:
      containers:
        - name: aws-pod
          imagePullPolicy: Never
          image: aws:kub
          ports:
            - containerPort: 7022
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-user-service
spec:
  selector:
    type: scraper-aws-pod
  ports:
    - name: user-access-point
      protocol: TCP
      port: 7022
      targetPort: 7022
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-scraper-service
spec:
  selector:
    type: scraper-scraper-pod
  ports:
    - protocol: TCP
      port: 7021
      targetPort: 7021
